# Day 3 Assignment

In [1]:
# Assignment 1
import numpy as np

In [2]:
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [4]:
# Assignment 3
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("No. of dimensions: ", arr.ndim)
print("Size of array: ", arr.size)


No. of dimensions:  2
Size of array:  6


In [5]:
# Assignment 4
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
l1 = []
n = int(input("Enter the list size : "))

print("\n")
for i in range(0, n):
    print("Enter number at location", i, ":")
    item = int(input())
    l1.append(item)
print("User List1 is ", l1)

l2 = []
print("\n")
for i in range(0, n):
    print("Enter number at location", i, ":")
    item = int(input())
    l2.append(item)
print("User List2 is ", l2)

arr1 = np.array(l1)
print(arr1)

arr2 = np.array(l2)
print(arr2)

arr = np.concatenate((arr1,arr2))
print(arr)

print(np.sort(arr))

Enter the list size : 5


Enter number at location 0 :
1
Enter number at location 1 :
3
Enter number at location 2 :
6
Enter number at location 3 :
4
Enter number at location 4 :
5
User List1 is  [1, 3, 6, 4, 5]


Enter number at location 0 :
2
Enter number at location 1 :
7
Enter number at location 2 :
8
Enter number at location 3 :
10
Enter number at location 4 :
9
User List2 is  [2, 7, 8, 10, 9]
[1 3 6 4 5]
[ 2  7  8 10  9]
[ 1  3  6  4  5  2  7  8 10  9]
[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]]) 
  
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a, b))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a, b))) 

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]
